package com.ithb.model;
// Generated Apr 8, 2013 2:36:02 PM by Hibernate Tools 3.2.1.GA



/**
 * AbsenId generated by hbm2java
 */
public class AbsenId  implements java.io.Serializable {


     private String nim;
     private String kodeKelas;
     private String nip;
     private String kodeMatkul;

    public AbsenId() {
    }

    public AbsenId(String nim, String kodeKelas, String nip, String kodeMatkul) {
       this.nim = nim;
       this.kodeKelas = kodeKelas;
       this.nip = nip;
       this.kodeMatkul = kodeMatkul;
    }
   
    public String getNim() {
        return this.nim;
    }
    
    public void setNim(String nim) {
        this.nim = nim;
    }
    public String getKodeKelas() {
        return this.kodeKelas;
    }
    
    public void setKodeKelas(String kodeKelas) {
        this.kodeKelas = kodeKelas;
    }
    public String getNip() {
        return this.nip;
    }
    
    public void setNip(String nip) {
        this.nip = nip;
    }
    public String getKodeMatkul() {
        return this.kodeMatkul;
    }
    
    public void setKodeMatkul(String kodeMatkul) {
        this.kodeMatkul = kodeMatkul;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AbsenId) ) return false;
		 AbsenId castOther = ( AbsenId ) other; 
         
		 return ( (this.getNim()==castOther.getNim()) || ( this.getNim()!=null && castOther.getNim()!=null && this.getNim().equals(castOther.getNim()) ) )
 && ( (this.getKodeKelas()==castOther.getKodeKelas()) || ( this.getKodeKelas()!=null && castOther.getKodeKelas()!=null && this.getKodeKelas().equals(castOther.getKodeKelas()) ) )
 && ( (this.getNip()==castOther.getNip()) || ( this.getNip()!=null && castOther.getNip()!=null && this.getNip().equals(castOther.getNip()) ) )
 && ( (this.getKodeMatkul()==castOther.getKodeMatkul()) || ( this.getKodeMatkul()!=null && castOther.getKodeMatkul()!=null && this.getKodeMatkul().equals(castOther.getKodeMatkul()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getNim() == null ? 0 : this.getNim().hashCode() );
         result = 37 * result + ( getKodeKelas() == null ? 0 : this.getKodeKelas().hashCode() );
         result = 37 * result + ( getNip() == null ? 0 : this.getNip().hashCode() );
         result = 37 * result + ( getKodeMatkul() == null ? 0 : this.getKodeMatkul().hashCode() );
         return result;
   }   


}


