package com.ithb.model;
// Generated Apr 8, 2013 2:36:02 PM by Hibernate Tools 3.2.1.GA



/**
 * BahanKuliah generated by hbm2java
 */
public class BahanKuliah  implements java.io.Serializable {


     private String kodeBahan;
     private MataKuliah mataKuliah;
     private String namaBahan;
     private byte[] bahan;

    public BahanKuliah() {
    }

	
    public BahanKuliah(String kodeBahan) {
        this.kodeBahan = kodeBahan;
    }
    public BahanKuliah(String kodeBahan, MataKuliah mataKuliah, String namaBahan, byte[] bahan) {
       this.kodeBahan = kodeBahan;
       this.mataKuliah = mataKuliah;
       this.namaBahan = namaBahan;
       this.bahan = bahan;
    }
   
    public String getKodeBahan() {
        return this.kodeBahan;
    }
    
    public void setKodeBahan(String kodeBahan) {
        this.kodeBahan = kodeBahan;
    }
    public MataKuliah getMataKuliah() {
        return this.mataKuliah;
    }
    
    public void setMataKuliah(MataKuliah mataKuliah) {
        this.mataKuliah = mataKuliah;
    }
    public String getNamaBahan() {
        return this.namaBahan;
    }
    
    public void setNamaBahan(String namaBahan) {
        this.namaBahan = namaBahan;
    }
    public byte[] getBahan() {
        return this.bahan;
    }
    
    public void setBahan(byte[] bahan) {
        this.bahan = bahan;
    }




}


