package com.ithb.model;
// Generated Apr 8, 2013 2:36:02 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Biaya generated by hbm2java
 */
public class Biaya  implements java.io.Serializable {


     private String kodeBiaya;
     private Integer biayaTetap;
     private Integer biayaSks;
     private Integer biayaPraktikum;
     private Integer biayaMhs;

    public Biaya() {
    }

	
    public Biaya(String kodeBiaya) {
        this.kodeBiaya = kodeBiaya;
    }
    public Biaya(String kodeBiaya, Integer biayaTetap, Integer biayaSks, Integer biayaPraktikum, Integer biayaMhs) {
       this.kodeBiaya = kodeBiaya;
       this.biayaTetap = biayaTetap;
       this.biayaSks = biayaSks;
       this.biayaPraktikum = biayaPraktikum;
       this.biayaMhs = biayaMhs;
    }
   
    public String getKodeBiaya() {
        return this.kodeBiaya;
    }
    
    public void setKodeBiaya(String kodeBiaya) {
        this.kodeBiaya = kodeBiaya;
    }
    public Integer getBiayaTetap() {
        return this.biayaTetap;
    }
    
    public void setBiayaTetap(Integer biayaTetap) {
        this.biayaTetap = biayaTetap;
    }
    public Integer getBiayaSks() {
        return this.biayaSks;
    }
    
    public void setBiayaSks(Integer biayaSks) {
        this.biayaSks = biayaSks;
    }
    public Integer getBiayaPraktikum() {
        return this.biayaPraktikum;
    }
    
    public void setBiayaPraktikum(Integer biayaPraktikum) {
        this.biayaPraktikum = biayaPraktikum;
    }
    public Integer getBiayaMhs() {
        return this.biayaMhs;
    }
    
    public void setBiayaMhs(Integer biayaMhs) {
        this.biayaMhs = biayaMhs;
    }



}


