package com.ithb.model;
// Generated Apr 8, 2013 2:36:02 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Mahasiswa generated by hbm2java
 */
public class Mahasiswa  implements java.io.Serializable {


     private String nim;
     private Pegawai pegawai;
     private Biaya biaya;
     private Departemen departemen;
     private String namaMhs;
     private String statusMhs;
     private Integer ipk;
     private String passMhs;
     private String teleponMhs;
     private String alamatMhs;
     private String jenisKelamin;

    public Mahasiswa() {
    }

	
    public Mahasiswa(String nim) {
        this.nim = nim;
    }
    public Mahasiswa(String nim, Pegawai pegawai, Biaya biaya, Departemen departemen, String namaMhs, String statusMhs, Integer ipk, String passMhs, String teleponMhs, String alamatMhs, String jenisKelamin) {
       this.nim = nim;
       this.pegawai = pegawai;
       this.biaya = biaya;
       this.departemen = departemen;
       this.namaMhs = namaMhs;
       this.statusMhs = statusMhs;
       this.ipk = ipk;
       this.passMhs = passMhs;
       this.teleponMhs = teleponMhs;
       this.alamatMhs = alamatMhs;
       this.jenisKelamin = jenisKelamin;
    }
   
    public String getNim() {
        return this.nim;
    }
    
    public void setNim(String nim) {
        this.nim = nim;
    }
    public Pegawai getPegawai() {
        return this.pegawai;
    }
    
    public void setPegawai(Pegawai pegawai) {
        this.pegawai = pegawai;
    }
    public Biaya getBiaya() {
        return this.biaya;
    }
    
    public void setBiaya(Biaya biaya) {
        this.biaya = biaya;
    }
    public Departemen getDepartemen() {
        return this.departemen;
    }
    
    public void setDepartemen(Departemen departemen) {
        this.departemen = departemen;
    }
    public String getNamaMhs() {
        return this.namaMhs;
    }
    
    public void setNamaMhs(String namaMhs) {
        this.namaMhs = namaMhs;
    }
    public String getStatusMhs() {
        return this.statusMhs;
    }
    
    public void setStatusMhs(String statusMhs) {
        this.statusMhs = statusMhs;
    }
    public Integer getIpk() {
        return this.ipk;
    }
    
    public void setIpk(Integer ipk) {
        this.ipk = ipk;
    }
    public String getPassMhs() {
        return this.passMhs;
    }
    
    public void setPassMhs(String passMhs) {
        this.passMhs = passMhs;
    }
    public String getTeleponMhs() {
        return this.teleponMhs;
    }
    
    public void setTeleponMhs(String teleponMhs) {
        this.teleponMhs = teleponMhs;
    }
    public String getAlamatMhs() {
        return this.alamatMhs;
    }
    
    public void setAlamatMhs(String alamatMhs) {
        this.alamatMhs = alamatMhs;
    }
    public String getJenisKelamin() {
        return this.jenisKelamin;
    }
    
    public void setJenisKelamin(String jenisKelamin) {
        this.jenisKelamin = jenisKelamin;
    }
    



}


