package com.ithb.model;
// Generated Apr 8, 2013 2:36:02 PM by Hibernate Tools 3.2.1.GA



/**
 * Pengumuman generated by hbm2java
 */
public class Pengumuman  implements java.io.Serializable {


     private String kodePengumuman;
     private Departemen departemen;
     private String judul;
     private String isi;

    public Pengumuman() {
    }

	
    public Pengumuman(String kodePengumuman) {
        this.kodePengumuman = kodePengumuman;
    }
    public Pengumuman(String kodePengumuman, Departemen departemen, String judul, String isi) {
       this.kodePengumuman = kodePengumuman;
       this.departemen = departemen;
       this.judul = judul;
       this.isi = isi;
    }
   
    public String getKodePengumuman() {
        return this.kodePengumuman;
    }
    
    public void setKodePengumuman(String kodePengumuman) {
        this.kodePengumuman = kodePengumuman;
    }
    public Departemen getDepartemen() {
        return this.departemen;
    }
    
    public void setDepartemen(Departemen departemen) {
        this.departemen = departemen;
    }
    public String getJudul() {
        return this.judul;
    }
    
    public void setJudul(String judul) {
        this.judul = judul;
    }
    public String getIsi() {
        return this.isi;
    }
    
    public void setIsi(String isi) {
        this.isi = isi;
    }




}


