package com.ithb.model;
// Generated Apr 8, 2013 2:36:02 PM by Hibernate Tools 3.2.1.GA



/**
 * Staff generated by hbm2java
 */
public class Staff  implements java.io.Serializable {


     private String nip;
     private Pegawai pegawai;
     private String passStaff;
     private String jabatan;

    public Staff() {
    }

	
    public Staff(String nip, Pegawai pegawai) {
        this.nip = nip;
        this.pegawai = pegawai;
    }
    public Staff(String nip, Pegawai pegawai, String passStaff, String jabatan) {
       this.nip = nip;
       this.pegawai = pegawai;
       this.passStaff = passStaff;
       this.jabatan = jabatan;
    }
   
    public String getNip() {
        return this.nip;
    }
    
    public void setNip(String nip) {
        this.nip = nip;
    }
    public Pegawai getPegawai() {
        return this.pegawai;
    }
    
    public void setPegawai(Pegawai pegawai) {
        this.pegawai = pegawai;
    }
    public String getPassStaff() {
        return this.passStaff;
    }
    
    public void setPassStaff(String passStaff) {
        this.passStaff = passStaff;
    }
    public String getJabatan() {
        return this.jabatan;
    }
    
    public void setJabatan(String jabatan) {
        this.jabatan = jabatan;
    }




}


