package com.ithb.model;
// Generated Apr 8, 2013 2:36:02 PM by Hibernate Tools 3.2.1.GA



/**
 * Absen generated by hbm2java
 */
public class Absen  implements java.io.Serializable {


     private AbsenId id;
     private Pegawai pegawai;
     private MataKuliah mataKuliah;
     private Mahasiswa mahasiswa;
     private Kelas kelas;
     private String statusKehadiran;

    public Absen() {
    }

	
    public Absen(AbsenId id, Pegawai pegawai, MataKuliah mataKuliah, Mahasiswa mahasiswa, Kelas kelas) {
        this.id = id;
        this.pegawai = pegawai;
        this.mataKuliah = mataKuliah;
        this.mahasiswa = mahasiswa;
        this.kelas = kelas;
    }
    public Absen(AbsenId id, Pegawai pegawai, MataKuliah mataKuliah, Mahasiswa mahasiswa, Kelas kelas, String statusKehadiran) {
       this.id = id;
       this.pegawai = pegawai;
       this.mataKuliah = mataKuliah;
       this.mahasiswa = mahasiswa;
       this.kelas = kelas;
       this.statusKehadiran = statusKehadiran;
    }
   
    public AbsenId getId() {
        return this.id;
    }
    
    public void setId(AbsenId id) {
        this.id = id;
    }
    public Pegawai getPegawai() {
        return this.pegawai;
    }
    
    public void setPegawai(Pegawai pegawai) {
        this.pegawai = pegawai;
    }
    public MataKuliah getMataKuliah() {
        return this.mataKuliah;
    }
    
    public void setMataKuliah(MataKuliah mataKuliah) {
        this.mataKuliah = mataKuliah;
    }
    public Mahasiswa getMahasiswa() {
        return this.mahasiswa;
    }
    
    public void setMahasiswa(Mahasiswa mahasiswa) {
        this.mahasiswa = mahasiswa;
    }
    public Kelas getKelas() {
        return this.kelas;
    }
    
    public void setKelas(Kelas kelas) {
        this.kelas = kelas;
    }
    public String getStatusKehadiran() {
        return this.statusKehadiran;
    }
    
    public void setStatusKehadiran(String statusKehadiran) {
        this.statusKehadiran = statusKehadiran;
    }




}


