package com.ithb.model;
// Generated Apr 8, 2013 2:36:02 PM by Hibernate Tools 3.2.1.GA



/**
 * BadanHukum generated by hbm2java
 */
public class BadanHukum  implements java.io.Serializable {


     private String kodeBhukum;
     private Fasilitas fasilitas;
     private String namaBhukum;
     private String tanggalBerdiri;
     private String nomorAkta;
     private String tanggalAkta;
     private String kota;
     private String alamat;
     private String kodePos;
     private String nomorPengesahan;
     private String tanggalPengesahan;
     private String telepon;
     private String faks;
     private String homepage;
     private String email;

    public BadanHukum() {
    }

	
    public BadanHukum(String kodeBhukum) {
        this.kodeBhukum = kodeBhukum;
    }
    public BadanHukum(String kodeBhukum, Fasilitas fasilitas, String namaBhukum, String tanggalBerdiri, String nomorAkta, String tanggalAkta, String kota, String alamat, String kodePos, String nomorPengesahan, String tanggalPengesahan, String telepon, String faks, String homepage, String email) {
       this.kodeBhukum = kodeBhukum;
       this.fasilitas = fasilitas;
       this.namaBhukum = namaBhukum;
       this.tanggalBerdiri = tanggalBerdiri;
       this.nomorAkta = nomorAkta;
       this.tanggalAkta = tanggalAkta;
       this.kota = kota;
       this.alamat = alamat;
       this.kodePos = kodePos;
       this.nomorPengesahan = nomorPengesahan;
       this.tanggalPengesahan = tanggalPengesahan;
       this.telepon = telepon;
       this.faks = faks;
       this.homepage = homepage;
       this.email = email;
    }
   
    public String getKodeBhukum() {
        return this.kodeBhukum;
    }
    
    public void setKodeBhukum(String kodeBhukum) {
        this.kodeBhukum = kodeBhukum;
    }
    public Fasilitas getFasilitas() {
        return this.fasilitas;
    }
    
    public void setFasilitas(Fasilitas fasilitas) {
        this.fasilitas = fasilitas;
    }
    public String getNamaBhukum() {
        return this.namaBhukum;
    }
    
    public void setNamaBhukum(String namaBhukum) {
        this.namaBhukum = namaBhukum;
    }
    public String getTanggalBerdiri() {
        return this.tanggalBerdiri;
    }
    
    public void setTanggalBerdiri(String tanggalBerdiri) {
        this.tanggalBerdiri = tanggalBerdiri;
    }
    public String getNomorAkta() {
        return this.nomorAkta;
    }
    
    public void setNomorAkta(String nomorAkta) {
        this.nomorAkta = nomorAkta;
    }
    public String getTanggalAkta() {
        return this.tanggalAkta;
    }
    
    public void setTanggalAkta(String tanggalAkta) {
        this.tanggalAkta = tanggalAkta;
    }
    public String getKota() {
        return this.kota;
    }
    
    public void setKota(String kota) {
        this.kota = kota;
    }
    public String getAlamat() {
        return this.alamat;
    }
    
    public void setAlamat(String alamat) {
        this.alamat = alamat;
    }
    public String getKodePos() {
        return this.kodePos;
    }
    
    public void setKodePos(String kodePos) {
        this.kodePos = kodePos;
    }
    public String getNomorPengesahan() {
        return this.nomorPengesahan;
    }
    
    public void setNomorPengesahan(String nomorPengesahan) {
        this.nomorPengesahan = nomorPengesahan;
    }
    public String getTanggalPengesahan() {
        return this.tanggalPengesahan;
    }
    
    public void setTanggalPengesahan(String tanggalPengesahan) {
        this.tanggalPengesahan = tanggalPengesahan;
    }
    public String getTelepon() {
        return this.telepon;
    }
    
    public void setTelepon(String telepon) {
        this.telepon = telepon;
    }
    public String getFaks() {
        return this.faks;
    }
    
    public void setFaks(String faks) {
        this.faks = faks;
    }
    public String getHomepage() {
        return this.homepage;
    }
    
    public void setHomepage(String homepage) {
        this.homepage = homepage;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


