package com.ithb.model;
// Generated Apr 8, 2013 2:36:02 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Departemen generated by hbm2java
 */
public class Departemen  implements java.io.Serializable {


     private String kodeDepart;
     private Pegawai pegawai;
     private Fakultas fakultas;
     private String namaDepart;

    public Departemen() {
    }

	
    public Departemen(String kodeDepart) {
        this.kodeDepart = kodeDepart;
    }
    public Departemen(String kodeDepart, Pegawai pegawai, Fakultas fakultas, String namaDepart) {
       this.kodeDepart = kodeDepart;
       this.pegawai = pegawai;
       this.fakultas = fakultas;
       this.namaDepart = namaDepart;
    }
   
    public String getKodeDepart() {
        return this.kodeDepart;
    }
    
    public void setKodeDepart(String kodeDepart) {
        this.kodeDepart = kodeDepart;
    }
    public Pegawai getPegawai() {
        return this.pegawai;
    }
    
    public void setPegawai(Pegawai pegawai) {
        this.pegawai = pegawai;
    }
    public Fakultas getFakultas() {
        return this.fakultas;
    }
    
    public void setFakultas(Fakultas fakultas) {
        this.fakultas = fakultas;
    }
    public String getNamaDepart() {
        return this.namaDepart;
    }
    
    public void setNamaDepart(String namaDepart) {
        this.namaDepart = namaDepart;
    }
   
}


