package com.ithb.model;
// Generated Apr 8, 2013 2:36:02 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Fakultas generated by hbm2java
 */
public class Fakultas  implements java.io.Serializable {


     private String kodeFakultas;
     private String namaFakultas;

    public Fakultas() {
    }

	
    public Fakultas(String kodeFakultas) {
        this.kodeFakultas = kodeFakultas;
    }
    public Fakultas(String kodeFakultas, String namaFakultas) {
       this.kodeFakultas = kodeFakultas;
       this.namaFakultas = namaFakultas;
    }
   
    public String getKodeFakultas() {
        return this.kodeFakultas;
    }
    
    public void setKodeFakultas(String kodeFakultas) {
        this.kodeFakultas = kodeFakultas;
    }
    public String getNamaFakultas() {
        return this.namaFakultas;
    }
    
    public void setNamaFakultas(String namaFakultas) {
        this.namaFakultas = namaFakultas;
    }


}


