package com.ithb.model;
// Generated Apr 8, 2013 2:36:02 PM by Hibernate Tools 3.2.1.GA



/**
 * HakAkses generated by hbm2java
 */
public class HakAkses  implements java.io.Serializable {


     private String kodeAkses;
     private String updateBadanHukum;
     private String updateDataFasilitas;
     private String updateMataKuliah;
     private String updateJadwalRuanganKelas;
     private String updateDataMahasiswaDanAlumni;
     private String updateDataStaffDanDosen;
     private String updatePengumuman;
     private String updateDataKeuangan;
     private String updateDataBiaya;
     private String updateDataPeriode;
     private String updateDataHakAkses;
     private String programStudi;
     private String inputBobotNilai;
     private String inputNilaiMahasiswa;
     private String inputAbsensiMahasiswa;
     private String inputBahanTugasKuliah;
     private String frsOnline;
     private String krsOnline;
     private String kartuHasilStudi;
     private String transkripNilaiResmiDanHistori;
     private String laporanKeuangan;
     private String viewPengumuman;
     private String isiKritikDanSaran;
     private String viewAbsensiMahasiswa;
     private String forumKritikDanSaran;
     private String acceptFrsOnline;

    public HakAkses() {
    }

	
    public HakAkses(String kodeAkses) {
        this.kodeAkses = kodeAkses;
    }
    public HakAkses(String kodeAkses, String updateBadanHukum, String updateDataFasilitas, String updateMataKuliah, String updateJadwalRuanganKelas, String updateDataMahasiswaDanAlumni, String updateDataStaffDanDosen, String updatePengumuman, String updateDataKeuangan, String updateDataBiaya, String updateDataPeriode, String updateDataHakAkses, String programStudi, String inputBobotNilai, String inputNilaiMahasiswa, String inputAbsensiMahasiswa, String inputBahanTugasKuliah, String frsOnline, String krsOnline, String kartuHasilStudi, String transkripNilaiResmiDanHistori, String laporanKeuangan, String viewPengumuman, String isiKritikDanSaran, String viewAbsensiMahasiswa, String forumKritikDanSaran, String acceptFrsOnline) {
       this.kodeAkses = kodeAkses;
       this.updateBadanHukum = updateBadanHukum;
       this.updateDataFasilitas = updateDataFasilitas;
       this.updateMataKuliah = updateMataKuliah;
       this.updateJadwalRuanganKelas = updateJadwalRuanganKelas;
       this.updateDataMahasiswaDanAlumni = updateDataMahasiswaDanAlumni;
       this.updateDataStaffDanDosen = updateDataStaffDanDosen;
       this.updatePengumuman = updatePengumuman;
       this.updateDataKeuangan = updateDataKeuangan;
       this.updateDataBiaya = updateDataBiaya;
       this.updateDataPeriode = updateDataPeriode;
       this.updateDataHakAkses = updateDataHakAkses;
       this.programStudi = programStudi;
       this.inputBobotNilai = inputBobotNilai;
       this.inputNilaiMahasiswa = inputNilaiMahasiswa;
       this.inputAbsensiMahasiswa = inputAbsensiMahasiswa;
       this.inputBahanTugasKuliah = inputBahanTugasKuliah;
       this.frsOnline = frsOnline;
       this.krsOnline = krsOnline;
       this.kartuHasilStudi = kartuHasilStudi;
       this.transkripNilaiResmiDanHistori = transkripNilaiResmiDanHistori;
       this.laporanKeuangan = laporanKeuangan;
       this.viewPengumuman = viewPengumuman;
       this.isiKritikDanSaran = isiKritikDanSaran;
       this.viewAbsensiMahasiswa = viewAbsensiMahasiswa;
       this.forumKritikDanSaran = forumKritikDanSaran;
       this.acceptFrsOnline = acceptFrsOnline;
    }
   
    public String getKodeAkses() {
        return this.kodeAkses;
    }
    
    public void setKodeAkses(String kodeAkses) {
        this.kodeAkses = kodeAkses;
    }
    public String getUpdateBadanHukum() {
        return this.updateBadanHukum;
    }
    
    public void setUpdateBadanHukum(String updateBadanHukum) {
        this.updateBadanHukum = updateBadanHukum;
    }
    public String getUpdateDataFasilitas() {
        return this.updateDataFasilitas;
    }
    
    public void setUpdateDataFasilitas(String updateDataFasilitas) {
        this.updateDataFasilitas = updateDataFasilitas;
    }
    public String getUpdateMataKuliah() {
        return this.updateMataKuliah;
    }
    
    public void setUpdateMataKuliah(String updateMataKuliah) {
        this.updateMataKuliah = updateMataKuliah;
    }
    public String getUpdateJadwalRuanganKelas() {
        return this.updateJadwalRuanganKelas;
    }
    
    public void setUpdateJadwalRuanganKelas(String updateJadwalRuanganKelas) {
        this.updateJadwalRuanganKelas = updateJadwalRuanganKelas;
    }
    public String getUpdateDataMahasiswaDanAlumni() {
        return this.updateDataMahasiswaDanAlumni;
    }
    
    public void setUpdateDataMahasiswaDanAlumni(String updateDataMahasiswaDanAlumni) {
        this.updateDataMahasiswaDanAlumni = updateDataMahasiswaDanAlumni;
    }
    public String getUpdateDataStaffDanDosen() {
        return this.updateDataStaffDanDosen;
    }
    
    public void setUpdateDataStaffDanDosen(String updateDataStaffDanDosen) {
        this.updateDataStaffDanDosen = updateDataStaffDanDosen;
    }
    public String getUpdatePengumuman() {
        return this.updatePengumuman;
    }
    
    public void setUpdatePengumuman(String updatePengumuman) {
        this.updatePengumuman = updatePengumuman;
    }
    public String getUpdateDataKeuangan() {
        return this.updateDataKeuangan;
    }
    
    public void setUpdateDataKeuangan(String updateDataKeuangan) {
        this.updateDataKeuangan = updateDataKeuangan;
    }
    public String getUpdateDataBiaya() {
        return this.updateDataBiaya;
    }
    
    public void setUpdateDataBiaya(String updateDataBiaya) {
        this.updateDataBiaya = updateDataBiaya;
    }
    public String getUpdateDataPeriode() {
        return this.updateDataPeriode;
    }
    
    public void setUpdateDataPeriode(String updateDataPeriode) {
        this.updateDataPeriode = updateDataPeriode;
    }
    public String getUpdateDataHakAkses() {
        return this.updateDataHakAkses;
    }
    
    public void setUpdateDataHakAkses(String updateDataHakAkses) {
        this.updateDataHakAkses = updateDataHakAkses;
    }
    public String getProgramStudi() {
        return this.programStudi;
    }
    
    public void setProgramStudi(String programStudi) {
        this.programStudi = programStudi;
    }
    public String getInputBobotNilai() {
        return this.inputBobotNilai;
    }
    
    public void setInputBobotNilai(String inputBobotNilai) {
        this.inputBobotNilai = inputBobotNilai;
    }
    public String getInputNilaiMahasiswa() {
        return this.inputNilaiMahasiswa;
    }
    
    public void setInputNilaiMahasiswa(String inputNilaiMahasiswa) {
        this.inputNilaiMahasiswa = inputNilaiMahasiswa;
    }
    public String getInputAbsensiMahasiswa() {
        return this.inputAbsensiMahasiswa;
    }
    
    public void setInputAbsensiMahasiswa(String inputAbsensiMahasiswa) {
        this.inputAbsensiMahasiswa = inputAbsensiMahasiswa;
    }
    public String getInputBahanTugasKuliah() {
        return this.inputBahanTugasKuliah;
    }
    
    public void setInputBahanTugasKuliah(String inputBahanTugasKuliah) {
        this.inputBahanTugasKuliah = inputBahanTugasKuliah;
    }
    public String getFrsOnline() {
        return this.frsOnline;
    }
    
    public void setFrsOnline(String frsOnline) {
        this.frsOnline = frsOnline;
    }
    public String getKrsOnline() {
        return this.krsOnline;
    }
    
    public void setKrsOnline(String krsOnline) {
        this.krsOnline = krsOnline;
    }
    public String getKartuHasilStudi() {
        return this.kartuHasilStudi;
    }
    
    public void setKartuHasilStudi(String kartuHasilStudi) {
        this.kartuHasilStudi = kartuHasilStudi;
    }
    public String getTranskripNilaiResmiDanHistori() {
        return this.transkripNilaiResmiDanHistori;
    }
    
    public void setTranskripNilaiResmiDanHistori(String transkripNilaiResmiDanHistori) {
        this.transkripNilaiResmiDanHistori = transkripNilaiResmiDanHistori;
    }
    public String getLaporanKeuangan() {
        return this.laporanKeuangan;
    }
    
    public void setLaporanKeuangan(String laporanKeuangan) {
        this.laporanKeuangan = laporanKeuangan;
    }
    public String getViewPengumuman() {
        return this.viewPengumuman;
    }
    
    public void setViewPengumuman(String viewPengumuman) {
        this.viewPengumuman = viewPengumuman;
    }
    public String getIsiKritikDanSaran() {
        return this.isiKritikDanSaran;
    }
    
    public void setIsiKritikDanSaran(String isiKritikDanSaran) {
        this.isiKritikDanSaran = isiKritikDanSaran;
    }
    public String getViewAbsensiMahasiswa() {
        return this.viewAbsensiMahasiswa;
    }
    
    public void setViewAbsensiMahasiswa(String viewAbsensiMahasiswa) {
        this.viewAbsensiMahasiswa = viewAbsensiMahasiswa;
    }
    public String getForumKritikDanSaran() {
        return this.forumKritikDanSaran;
    }
    
    public void setForumKritikDanSaran(String forumKritikDanSaran) {
        this.forumKritikDanSaran = forumKritikDanSaran;
    }
    public String getAcceptFrsOnline() {
        return this.acceptFrsOnline;
    }
    
    public void setAcceptFrsOnline(String acceptFrsOnline) {
        this.acceptFrsOnline = acceptFrsOnline;
    }




}


