package com.ithb.model;
// Generated Apr 8, 2013 2:36:02 PM by Hibernate Tools 3.2.1.GA



/**
 * Jadwal generated by hbm2java
 */
public class Jadwal  implements java.io.Serializable {


     private JadwalId id;
     private Pegawai pegawai;
     private MataKuliah mataKuliah;
     private Kelas kelas;

    public Jadwal() {
    }

    public Jadwal(JadwalId id, Pegawai pegawai, MataKuliah mataKuliah, Kelas kelas) {
       this.id = id;
       this.pegawai = pegawai;
       this.mataKuliah = mataKuliah;
       this.kelas = kelas;
    }
   
    public JadwalId getId() {
        return this.id;
    }
    
    public void setId(JadwalId id) {
        this.id = id;
    }
    public Pegawai getPegawai() {
        return this.pegawai;
    }
    
    public void setPegawai(Pegawai pegawai) {
        this.pegawai = pegawai;
    }
    public MataKuliah getMataKuliah() {
        return this.mataKuliah;
    }
    
    public void setMataKuliah(MataKuliah mataKuliah) {
        this.mataKuliah = mataKuliah;
    }
    public Kelas getKelas() {
        return this.kelas;
    }
    
    public void setKelas(Kelas kelas) {
        this.kelas = kelas;
    }




}


