package com.ithb.model;
// Generated Apr 8, 2013 2:36:02 PM by Hibernate Tools 3.2.1.GA



/**
 * KritikSaran generated by hbm2java
 */
public class KritikSaran  implements java.io.Serializable {


     private String kodeKritik;
     private Mahasiswa mahasiswa;
     private String isiKritik;

    public KritikSaran() {
    }

	
    public KritikSaran(String kodeKritik) {
        this.kodeKritik = kodeKritik;
    }
    public KritikSaran(String kodeKritik, Mahasiswa mahasiswa, String isiKritik) {
       this.kodeKritik = kodeKritik;
       this.mahasiswa = mahasiswa;
       this.isiKritik = isiKritik;
    }
   
    public String getKodeKritik() {
        return this.kodeKritik;
    }
    
    public void setKodeKritik(String kodeKritik) {
        this.kodeKritik = kodeKritik;
    }
    public Mahasiswa getMahasiswa() {
        return this.mahasiswa;
    }
    
    public void setMahasiswa(Mahasiswa mahasiswa) {
        this.mahasiswa = mahasiswa;
    }
    public String getIsiKritik() {
        return this.isiKritik;
    }
    
    public void setIsiKritik(String isiKritik) {
        this.isiKritik = isiKritik;
    }




}


