package com.ithb.model;
// Generated Apr 8, 2013 2:36:02 PM by Hibernate Tools 3.2.1.GA



/**
 * NilaiId generated by hbm2java
 */
public class NilaiId  implements java.io.Serializable {


     private String nim;
     private String kodeMatkul;

    public NilaiId() {
    }

    public NilaiId(String nim, String kodeMatkul) {
       this.nim = nim;
       this.kodeMatkul = kodeMatkul;
    }
   
    public String getNim() {
        return this.nim;
    }
    
    public void setNim(String nim) {
        this.nim = nim;
    }
    public String getKodeMatkul() {
        return this.kodeMatkul;
    }
    
    public void setKodeMatkul(String kodeMatkul) {
        this.kodeMatkul = kodeMatkul;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof NilaiId) ) return false;
		 NilaiId castOther = ( NilaiId ) other; 
         
		 return ( (this.getNim()==castOther.getNim()) || ( this.getNim()!=null && castOther.getNim()!=null && this.getNim().equals(castOther.getNim()) ) )
 && ( (this.getKodeMatkul()==castOther.getKodeMatkul()) || ( this.getKodeMatkul()!=null && castOther.getKodeMatkul()!=null && this.getKodeMatkul().equals(castOther.getKodeMatkul()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getNim() == null ? 0 : this.getNim().hashCode() );
         result = 37 * result + ( getKodeMatkul() == null ? 0 : this.getKodeMatkul().hashCode() );
         return result;
   }   


}


