package com.ithb.model;
// Generated Apr 8, 2013 2:36:02 PM by Hibernate Tools 3.2.1.GA



/**
 * Nilai generated by hbm2java
 */
public class Nilai  implements java.io.Serializable {


     private NilaiId id;
     private MataKuliah mataKuliah;
     private Mahasiswa mahasiswa;
     private String indeks;
     private String semester;
     private Integer nilai1;
     private Integer nilai2;
     private Integer nilai3;
     private Integer nilai4;
     private Integer nilai5;
     private Integer uas;

    public Nilai() {
    }

	
    public Nilai(NilaiId id, MataKuliah mataKuliah, Mahasiswa mahasiswa) {
        this.id = id;
        this.mataKuliah = mataKuliah;
        this.mahasiswa = mahasiswa;
    }
    public Nilai(NilaiId id, MataKuliah mataKuliah, Mahasiswa mahasiswa, String indeks, String semester, Integer nilai1, Integer nilai2, Integer nilai3, Integer nilai4, Integer nilai5, Integer uas) {
       this.id = id;
       this.mataKuliah = mataKuliah;
       this.mahasiswa = mahasiswa;
       this.indeks = indeks;
       this.semester = semester;
       this.nilai1 = nilai1;
       this.nilai2 = nilai2;
       this.nilai3 = nilai3;
       this.nilai4 = nilai4;
       this.nilai5 = nilai5;
       this.uas = uas;
    }
   
    public NilaiId getId() {
        return this.id;
    }
    
    public void setId(NilaiId id) {
        this.id = id;
    }
    public MataKuliah getMataKuliah() {
        return this.mataKuliah;
    }
    
    public void setMataKuliah(MataKuliah mataKuliah) {
        this.mataKuliah = mataKuliah;
    }
    public Mahasiswa getMahasiswa() {
        return this.mahasiswa;
    }
    
    public void setMahasiswa(Mahasiswa mahasiswa) {
        this.mahasiswa = mahasiswa;
    }
    public String getIndeks() {
        return this.indeks;
    }
    
    public void setIndeks(String indeks) {
        this.indeks = indeks;
    }
    public String getSemester() {
        return this.semester;
    }
    
    public void setSemester(String semester) {
        this.semester = semester;
    }
    public Integer getNilai1() {
        return this.nilai1;
    }
    
    public void setNilai1(Integer nilai1) {
        this.nilai1 = nilai1;
    }
    public Integer getNilai2() {
        return this.nilai2;
    }
    
    public void setNilai2(Integer nilai2) {
        this.nilai2 = nilai2;
    }
    public Integer getNilai3() {
        return this.nilai3;
    }
    
    public void setNilai3(Integer nilai3) {
        this.nilai3 = nilai3;
    }
    public Integer getNilai4() {
        return this.nilai4;
    }
    
    public void setNilai4(Integer nilai4) {
        this.nilai4 = nilai4;
    }
    public Integer getNilai5() {
        return this.nilai5;
    }
    
    public void setNilai5(Integer nilai5) {
        this.nilai5 = nilai5;
    }
    public Integer getUas() {
        return this.uas;
    }
    
    public void setUas(Integer uas) {
        this.uas = uas;
    }




}


