package com.ithb.model;
// Generated Apr 8, 2013 2:36:02 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Pegawai generated by hbm2java
 */
public class Pegawai  implements java.io.Serializable {


     private String nip;
     private String namaPegawai;

    public Pegawai() {
    }

	
    public Pegawai(String nip) {
        this.nip = nip;
    }
    public Pegawai(String nip, String namaPegawai) {
       this.nip = nip;
       this.namaPegawai = namaPegawai;
    }
   
    public String getNip() {
        return this.nip;
    }
    
    public void setNip(String nip) {
        this.nip = nip;
    }
    public String getNamaPegawai() {
        return this.namaPegawai;
    }
    
    public void setNamaPegawai(String namaPegawai) {
        this.namaPegawai = namaPegawai;
    }
    



}


