package com.ithb.model;
// Generated Apr 8, 2013 2:36:02 PM by Hibernate Tools 3.2.1.GA



/**
 * Periode generated by hbm2java
 */
public class Periode  implements java.io.Serializable {


     private String kodePeriode;
     private Departemen departemen;
     private String namaPeriode;
     private String awal;
     private String akhir;

    public Periode() {
    }

	
    public Periode(String kodePeriode) {
        this.kodePeriode = kodePeriode;
    }
    public Periode(String kodePeriode, Departemen departemen, String namaPeriode, String awal, String akhir) {
       this.kodePeriode = kodePeriode;
       this.departemen = departemen;
       this.namaPeriode = namaPeriode;
       this.awal = awal;
       this.akhir = akhir;
    }
   
    public String getKodePeriode() {
        return this.kodePeriode;
    }
    
    public void setKodePeriode(String kodePeriode) {
        this.kodePeriode = kodePeriode;
    }
    public Departemen getDepartemen() {
        return this.departemen;
    }
    
    public void setDepartemen(Departemen departemen) {
        this.departemen = departemen;
    }
    public String getNamaPeriode() {
        return this.namaPeriode;
    }
    
    public void setNamaPeriode(String namaPeriode) {
        this.namaPeriode = namaPeriode;
    }
    public String getAwal() {
        return this.awal;
    }
    
    public void setAwal(String awal) {
        this.awal = awal;
    }
    public String getAkhir() {
        return this.akhir;
    }
    
    public void setAkhir(String akhir) {
        this.akhir = akhir;
    }




}


